// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          int64            `json:"id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Completed   pgtype.Bool      `json:"completed"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	UserID      pgtype.Int8      `json:"user_id"`
}

type User struct {
	ID        int64            `json:"id"`
	GoogleID  string           `json:"google_id"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
