// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	DeleteTodo(ctx context.Context, arg DeleteTodoParams) error
	GetCompletedTodos(ctx context.Context, userID pgtype.Int8) ([]Todo, error)
	GetPendingTodos(ctx context.Context, userID pgtype.Int8) ([]Todo, error)
	GetTodoById(ctx context.Context, arg GetTodoByIdParams) (Todo, error)
	GetTodos(ctx context.Context, userID pgtype.Int8) ([]Todo, error)
	GetTodosByDateRange(ctx context.Context, arg GetTodosByDateRangeParams) ([]Todo, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	MarkTodoAsCompleted(ctx context.Context, arg MarkTodoAsCompletedParams) (Todo, error)
	MarkTodoAsPending(ctx context.Context, arg MarkTodoAsPendingParams) (Todo, error)
	SearchTodos(ctx context.Context, arg SearchTodosParams) ([]Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
