// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	DeleteTodo(ctx context.Context, id int64) error
	GetCompletedTodos(ctx context.Context) ([]Todo, error)
	GetPendingTodos(ctx context.Context) ([]Todo, error)
	GetTodoById(ctx context.Context, id int64) (Todo, error)
	GetTodos(ctx context.Context) ([]Todo, error)
	GetTodosByDateRange(ctx context.Context, arg GetTodosByDateRangeParams) ([]Todo, error)
	MarkTodoAsCompleted(ctx context.Context, id int64) (Todo, error)
	MarkTodoAsPending(ctx context.Context, id int64) (Todo, error)
	SearchTodos(ctx context.Context, dollar_1 pgtype.Text) ([]Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
