// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (title, description, completed, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, completed, created_at, updated_at, user_id
`

type CreateTodoParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Completed   pgtype.Bool `json:"completed"`
	UserID      pgtype.Int8 `json:"user_id"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.UserID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const getCompletedTodos = `-- name: GetCompletedTodos :many
SELECT id, title, description, completed, created_at, updated_at, user_id FROM todos WHERE completed = true AND user_id = $1
`

func (q *Queries) GetCompletedTodos(ctx context.Context, userID pgtype.Int8) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getCompletedTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTodos = `-- name: GetPendingTodos :many
SELECT id, title, description, completed, created_at, updated_at, user_id FROM todos WHERE completed = false AND user_id = $1
`

func (q *Queries) GetPendingTodos(ctx context.Context, userID pgtype.Int8) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getPendingTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoById = `-- name: GetTodoById :one
SELECT id, title, description, completed, created_at, updated_at, user_id FROM todos WHERE id = $1
`

func (q *Queries) GetTodoById(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoById, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getTodos = `-- name: GetTodos :many
SELECT id, title, description, completed, created_at, updated_at, user_id
FROM todos WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTodos(ctx context.Context, userID pgtype.Int8) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosByDateRange = `-- name: GetTodosByDateRange :many
SELECT id, title, description, completed, created_at, updated_at, user_id FROM todos
WHERE user_id = $1 AND created_at BETWEEN $2 AND $3
`

type GetTodosByDateRangeParams struct {
	UserID      pgtype.Int8      `json:"user_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	CreatedAt_2 pgtype.Timestamp `json:"created_at_2"`
}

func (q *Queries) GetTodosByDateRange(ctx context.Context, arg GetTodosByDateRangeParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodosByDateRange, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTodoAsCompleted = `-- name: MarkTodoAsCompleted :one
UPDATE todos 
SET completed = true
WHERE id = $1
RETURNING id, title, description, completed, created_at, updated_at, user_id
`

func (q *Queries) MarkTodoAsCompleted(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRow(ctx, markTodoAsCompleted, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const markTodoAsPending = `-- name: MarkTodoAsPending :one
UPDATE todos
SET completed = false
WHERE id = $1
RETURNING id, title, description, completed, created_at, updated_at, user_id
`

func (q *Queries) MarkTodoAsPending(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRow(ctx, markTodoAsPending, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const searchTodos = `-- name: SearchTodos :many
SELECT id, title, description, completed, created_at, updated_at, user_id FROM todos
WHERE user_id = $1 AND (title ILIKE '%' || $2 || '%' OR description ILIKE '%' || $2 || '%')
`

type SearchTodosParams struct {
	UserID  pgtype.Int8 `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchTodos(ctx context.Context, arg SearchTodosParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, searchTodos, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos 
SET title = $1, description = $2, completed = $3
WHERE id = $4
RETURNING id, title, description, completed, created_at, updated_at, user_id
`

type UpdateTodoParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Completed   pgtype.Bool `json:"completed"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
